import type { Metadata } from "next";
import { Geist, Geist_Mono, Playfair } from "next/font/google";
import "../app/globals.css";

const playfair = Playfair({
  subsets: ['latin'],
  weight: ['400','600','700'],
  variable: '--font-geist-mono'
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${playfair.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
