import type { Metadata } from 'next'
import { Inter, EB_Garamond } from 'next/font/google'
import '../app/globals.css'
import { cn } from '@/lib/utils'
import { Providers } from '../components/Providers'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' })
const eb_garamond = EB_Garamond({
  subsets: ['latin'],
  variable: '--font-heading',
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en' className={cn(inter.variable, eb_garamond.variable)}>
      <body className='min-h-[calc(100vh-1px)] flex flex-col font-sans bg-brand-50 text-brand-950 antialiased'>
        <main className='relative flex-1 flex flex-col'>
          <Providers>{children}</Providers>
        </main>
      </body>
    </html>
  )
}
